language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: safe-ocean-22836
  api_key:
    secure: vINt68mP3MKMifJtDFPnhSInQuD9oSpmcgIOwHFLZ9HUDc8BHiR3AH0p1BpeIA5tVjg+QiGevqJUGpmm2zBJN4zpmOzOJPF8YgB0fp18GTHuvVNoKIzhPCmic3T66ilQEIC4YjtQq2iFGtO6zCgX6mDZKqnwi54Zxje4eNfSw/FYrOpVSVFGtDWRcv+mbPIwi3E8MF1ZAYvT/0aE21rWsJ/9IQxyDBEjt+HnfF4dpVKwgF+mTQLC18fFzHn4Eeg11M3DL5CILpg7Hav16GU8hl8l3Hf+cauaYBygoApttkKntlQLTr7z7AVMyFKNc7mJX0llhRpYSohVsg5rh/4LAfBGFt1Fu1bEvaefD2mqKAhjSdD5uv5UG6COg1BCh6Hfv/lYkza6Uvmg/uLilD/1VK6TtWNzbYhv0L6//qKBobbfCDd8q8AeTknoI+fhvGavPTIeG1Cls2p4f5R5jj1Y+1fS+KfGl6L6/9r57wuBqS2XsMxvsCRiIZ42NfKJcqFB0KeuHqxW2bF/XaTPl0jbMAdjqv4AKZp/MEpKEli1vBtpdSbbUTqqFhkvLL7IDl0UDSS6EIsNMFFcJl2Aa4keV66xkt9PJRufZuD+2vkfNZcZ/Igoj9lgo/V/hhsTfiiPoJ7Su+ScvIiRJvNg6OmLVedTOctl8rCLQtp7o5Y1nvo=
